#!/usr/bin/env python
# -*- coding: utf-8 -*-

import xmlrpclib
import sys
import os

port = 6969


if __name__ == '__main__':

    parts = [s.strip() for s in ' '.join(sys.argv[1:]).split('--')]
    while len(parts) < 3:
        parts += ['']
    summary, description, hosts = parts

    # La A sta per Alarm
    summary = summary or 'PA'

    hosts = hosts.split()
    if not hosts:
        with open(os.path.expanduser('~/.prrc')) as f:
            hosts = [h for h in map(str.strip, f) if h and not h.startswith('#')]

    for host in hosts:
        try:
            prd = xmlrpclib.ServerProxy('http://{}:{}'.format(host, port))
            prd.message(summary, description)
        except Exception as e:
            print >> sys.stderr, "Could not deliver to {}: {}".format(host, e)
            continue
