#!/usr/bin/env python
# -*- coding: utf-8 -*-

import xmlrpclib
import sys
import threading
import os

port = 6969


def send(host, summary, description):
    try:
        if ':' in host:
            host, _port = host.split(':')
        else:
            _port = port

        prd = xmlrpclib.ServerProxy('http://{}:{}'.format(host, int(_port)))
        prd.message(summary, description)
    except Exception as e:
        print >> sys.stderr, "Could not deliver to {}: {}".format(host, e)


if __name__ == '__main__':

    parts = [s.strip() for s in ' '.join(sys.argv[1:]).split('--')]
    while len(parts) < 3:
        parts += ['']
    summary, description, hosts = parts

    # La A sta per Alarm
    summary = summary or 'PA'

    hosts = hosts.split()
    if not hosts:
        with open(os.path.expanduser('~/.prrc')) as f:
            hosts = [h for h in map(str.strip, f) if h and not h.startswith('#')]

    threads = []
    for host in hosts:
        ht = threading.Thread(target=send, args=(host, summary, description))
        threads.append(ht)
        ht.start()

    for ht in threads:
        ht.join(5.0)
